version: 2

updates:
  # —–––––– Common defaults for all ecosystems ––––––—
  - &common
    package-ecosystem: "npm"
    directory: "/user-workspace/ai-cli-tool"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    versioning-strategy: "auto"
    labels:
      - "npm"
      - "dependencies"
      - "security"
    commit-message:
      prefix: "npm"
      include: "scope"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "CrzyHAX91"

  # —–––––– Reuse all common, alleen path wijzigen ––––––—
  - <<: *common
    directory: "/user-workspace/ai-cli-web"

  # —–––––– Python/Pip service ––––––—
  - <<: *common
    package-ecosystem: "pip"
    directory: "/user-workspace/flask-api-service"
    labels:
      - "pip"
      - "dependencies"
      - "security"
    commit-message:
      prefix: "pip"
      include: "scope"

  # —–––––– GitHub Actions updates ––––––—
  - <<: *common
    package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "github-actions"
      - "dependencies"
      - "security"
    commit-message:
      prefix: "github-actions"
      include: "scope"

  # —–––––– Docker‐image updates ––––––—
  - <<: *common
    package-ecosystem: "docker"
    directory: "/"
    labels:
      - "docker"
      - "dependencies"
      - "security"
    commit-message:
      prefix: "docker"
      include: "scope"
