version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Labels on pull requests for version updates
    labels:
      - "npm dependencies"
      - "security"
    # Specify target branch for pull requests
    target-branch: "main"
    # Add reviewers
    reviewers:
      - "CrzyHAX91"
    # Add assignees
    assignees:
      - "CrzyHAX91"
    # Configure commit message options
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Configure versioning strategy
    versioning-strategy:
      lockfile-only: false
      auto: true
    # Configure pull request settings
    pull-request-branch-name:
      separator: "-"
    # Configure security updates
    security-updates-only: false
    # Configure dependency type updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
