version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "node-fetch"
        versions: ["4.x"]
