version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "CrzyHAX91"
    assignees:
      - "CrzyHAX91"
    ignore:
      - dependency-name: "react-scripts"
        versions: ["5.x"]  # Ignore major updates to react-scripts
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    rebase-strategy: "auto"
    target-branch: "main"
