name: MS Security DevOps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 1'         # Elke maandag om 02:00 UTC
  workflow_dispatch:           # Handmatig triggerbaar

permissions:
  contents: read
  security-events: write
  id-token: write

concurrency:
  group: msdo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  msdo:
    name: Microsoft Security DevOps
    runs-on: windows-latest
    timeout-minutes: 30

    strategy:
      matrix:
        dotnet-version: [ '5.0.x', '6.0.x' ]
        node-version:   [ '16.x' ]

    steps:
      - name: Checkout code
        uses: a

