name: Security & Dependency Updates

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'requirements.txt'
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

concurrency:
  group: security-deps-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  id-token: write
  security-events: write  # Ensure this permission is correctly defined

jobs:
  audit:
    name: Audit Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run npm audit
        run: |
          npm install
          npm audit fix

      - name: Run safety check
        run: |
          pip install safety
          safety check

      - name: Upload Audit Report
        uses: actions/upload-artifact@v2
        with:
          name: audit-report

on:
  workflow_run:
    workflows: ["Audit Workflow"]
    types:
      - completed

jobs:
  create-pr:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}  # Only create PR if the audit fails
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): security & dependency updates'
          title: 'chore: Security & Dependency Updates'
          body: |
            This PR contains automatically generated updates:
            - `npm audit fix` for Node.js projects
            - `safety check` for Python projects

