name: Security and Dependency Updates

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  push:
    branches: [ main ]
    paths:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/requirements.txt'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/pip
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      # Node.js Security Checks
      - name: Check AI CLI Tool
        working-directory: user-workspace/ai-cli-tool
        run: |
          npm ci
          npm audit fix --force
          npm audit
          
      - name: Check Web Interface
        working-directory: user-workspace/ai-cli-web
        run: |
          npm ci
          npm audit fix --force
          npm audit

      # Python Security Checks
      - name: Check Flask API
        working-directory: user-workspace/flask-api-service
        run: |
          pip install -r requirements.txt
          pip install safety
          safety check

      # Create Pull Request if needed
      - name: Create Pull Request for Security Updates
        if: failure()
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Security: Update dependencies to fix vulnerabilities"
          title: "Security: Dependency Updates"
          body: |
            This PR contains security updates for dependencies.
            
            Changes made:
            - Run npm audit fix for Node.js projects
            - Update Python dependencies with known vulnerabilities
            - Update package-lock.json files
            
            Please review the changes carefully before merging.
          branch: security-updates
          base: main
          labels: security,dependencies

  dependency-updates:
    name: Dependency Updates
    runs-on: ubuntu-latest
    needs: security-checks

    steps:
      - uses: actions/checkout@v4

      - name: Update Node.js Dependencies
        run: |
          for dir in user-workspace/ai-cli-tool user-workspace/ai-cli-web; do
            if [ -f "$dir/package.json" ]; then
              cd $dir
              npm update
              npm install
              cd -
            fi
          done

      - name: Update Python Dependencies
        run: |
          cd user-workspace/flask-api-service
          pip install -r requirements.txt
          pip list --outdated --format=json | python -c "
          import json, sys
          pkgs = json.load(sys.stdin)
          with open('requirements.txt', 'r') as f:
              reqs = f.readlines()
          with open('requirements.txt', 'w') as f:
              for req in reqs:
                  pkg_name = req.split('==')[0].strip()
                  for pkg in pkgs:
                      if pkg['name'] == pkg_name:
                          f.write(f'{pkg_name}=={pkg[\"latest_version\"]}\n')
                          break
                  else:
                      f.write(req)
          "

      - name: Create Pull Request for Updates
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Chore: Update dependencies to latest versions"
          title: "Chore: Dependency Updates"
          body: |
            This PR updates dependencies to their latest versions.
            
            Updates made:
            - Node.js dependencies updated
            - Python dependencies updated
            - Package lock files regenerated
            
            Please review the changes and run tests before merging.
          branch: dependency-updates
          base: main
          labels: dependencies

  vulnerability-scan:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    needs: [security-checks, dependency-updates]

    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          languages: javascript, python

      - name: Create Issue for High Severity Vulnerabilities
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/VULNERABILITY_ISSUE_TEMPLATE.md

  notify:
    name: Notification
    runs-on: ubuntu-latest
    needs: [security-checks, dependency-updates, vulnerability-scan]
    if: always()

    steps:
      - name: Notify on Success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'security-updates'
          slack-message: "Security checks and dependency updates completed successfully! :white_check_mark:"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'security-updates'
          slack-message: "Security checks or dependency updates failed! :x: Please check the workflow logs."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
