name: Security and Dependency Updates

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily
  push:
    branches: [ main ]
    paths:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/requirements.txt'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      node-versions: ${{ steps.set-matrix.outputs.node-versions }}
      python-versions: ${{ steps.set-matrix.outputs.python-versions }}
    steps:
      - id: set-matrix
        run: |
          echo "node-versions=[\"18.x\"]" >> $GITHUB_OUTPUT
          echo "python-versions=[\"3.11\"]" >> $GITHUB_OUTPUT

  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4

      # Node.js Setup and Audit
      - name: Set up Node.js
        uses:

